### ISSUE TITLE
Exit environmental call gives wrong exit code.

### ISSUE THREAD

**Issue by Icarusradio** [ThaumicMekanism/venus#2]
According to the wiki, the exit environmental call should exit the program (exit status should be 0).
However, the following code:

```
addi a0, x0, 1
addi a1, x0, 42
ecall
addi a0, x0, 10
addi a1, x0, 100
ecall
```

gives exit code 100 (which is value in a1). I don't think this is correct.

**Comment by ThaumicMekanism** [comment]
Ya you are right. I recently made some internal changes to support error codes when returning from main but seems I screwed it up still. I’ll fix it soon.

**Comment by ThaumicMekanism** [comment]
Actually I know what the issue is. It is exiting with error code 0 (because of what it’s printing) though just displaying the incorrect code because I forgot to set the error code to 0 in that ecall even though I cause the program to exit. I’ll have a fix in less than an hour (after I get back to my computer)

**Comment by ThaumicMekanism** [comment]
Fixed. Once it finished building, you may need to reset your browser cache or download the new jvm version.

With backend commit: 
- https://github.com/ThaumicMekanism/venusbackend/commit/27f9f24ed0ac7d6b5eadc8744aad6baf15a3c305

And frontend commits:
- js: https://github.com/ThaumicMekanism/venus/commit/eaf700faa4b1c6bc781c444d62b55493829fcac4
- jvm: https://github.com/ThaumicMekanism/venus/commit/1030ee241fd249e5950c6688cca882c5b265cb06
